package cn.ai.sales.module.agent.enums;

public interface AgentConstants {

    int STATUS_ENABLE = 0;
    int STATUS_DISABLE = 1;

    String REPLY_MODE_MANUAL_CONFIRM = "MANUAL_CONFIRM";
    String REPLY_MODE_AUTO_REPLY = "AUTO_REPLY";
    /** @deprecated use {@link #REPLY_MODE_MANUAL_CONFIRM}. */
    @Deprecated
    String REPLY_MODE_MANUAL_ONLY = "MANUAL_ONLY";
    String REPLY_MODE_RECORD_ONLY = "RECORD_ONLY";
    int DEFAULT_QUIET_SECONDS = 90;
    String DEFAULT_BUSINESS_HOURS_START = "08:00";
    String DEFAULT_BUSINESS_HOURS_END = "22:00";

    int LOGIN_STATUS_UNKNOWN = 0;
    int LOGIN_STATUS_ONLINE = 1;
    int LOGIN_STATUS_OFFLINE = 2;
    int LOGIN_STATUS_EXPIRED = 3;

    String BIND_SESSION_WAIT_SCAN = "WAIT_SCAN";
    String BIND_SESSION_WAIT_CONFIRM = "WAIT_CONFIRM";
    String BIND_SESSION_BOUND = "BOUND";
    String BIND_SESSION_EXPIRED = "EXPIRED";
    String BIND_SESSION_FAILED = "FAILED";

    int CUSTOMER_LEVEL_NORMAL = 0;
    int CUSTOMER_LEVEL_TARGET = 1;
    int CUSTOMER_LEVEL_IMPORTANT = 2;

    int RISK_LEVEL_GREEN = 0;
    int RISK_LEVEL_YELLOW = 1;
    int RISK_LEVEL_RED = 2;

    int CONVERSATION_STATUS_OPEN = 0;
    int CONVERSATION_STATUS_AI_AUTO = 1;
    int CONVERSATION_STATUS_WAITING_CONFIRM = 2;
    int CONVERSATION_STATUS_HUMAN_TAKEOVER = 3;
    int CONVERSATION_STATUS_CLOSED = 4;

    String CONVERSATION_QUEUE_PENDING_REVIEW = "PENDING_REVIEW";
    String CONVERSATION_QUEUE_RISK = "RISK";
    String CONVERSATION_QUEUE_TAKEOVER = "TAKEOVER";
    String CONVERSATION_QUEUE_FOCUS = "FOCUS";
    String CONVERSATION_QUEUE_URGENT = "URGENT";

    String PURCHASE_INTENTION_LOW = "LOW";
    String PURCHASE_INTENTION_MEDIUM = "MEDIUM";
    String PURCHASE_INTENTION_HIGH = "HIGH";
    String PURCHASE_INTENTION_STRONG = "STRONG";

    String SALES_STAGE_NEW_LEAD = "NEW_LEAD";
    String SALES_STAGE_NEEDS_CONFIRMED = "NEEDS_CONFIRMED";
    String SALES_STAGE_PRODUCT_INTRO = "PRODUCT_INTRO";
    String SALES_STAGE_QUOTE_NEGOTIATION = "QUOTE_NEGOTIATION";
    String SALES_STAGE_DEAL_PROGRESS = "DEAL_PROGRESS";
    String SALES_STAGE_AFTER_SALES = "AFTER_SALES";

    String CUSTOMER_SENTIMENT_POSITIVE = "POSITIVE";
    String CUSTOMER_SENTIMENT_NEUTRAL = "NEUTRAL";
    String CUSTOMER_SENTIMENT_NEGATIVE = "NEGATIVE";

    String FOLLOW_UP_PRIORITY_NORMAL = "NORMAL";
    String FOLLOW_UP_PRIORITY_FOCUS = "FOCUS";
    String FOLLOW_UP_PRIORITY_URGENT = "URGENT";

    int MESSAGE_DIRECTION_INBOUND = 1;
    int MESSAGE_DIRECTION_OUTBOUND = 2;

    int SENDER_CUSTOMER = 1;
    int SENDER_AI_AGENT = 2;
    int SENDER_HUMAN_ADVISOR = 3;
    int SENDER_SYSTEM = 4;

    int MESSAGE_TYPE_UNKNOWN = 0;
    int MESSAGE_TYPE_TEXT = 1;
    int MESSAGE_TYPE_IMAGE = 3;
    int MESSAGE_TYPE_VOICE = 34;
    int MESSAGE_TYPE_VIDEO = 43;
    int MESSAGE_TYPE_EMOJI = 47;
    int MESSAGE_TYPE_FILE_OR_LINK = 49;

    int SEND_STATUS_RECEIVED = 0;
    int SEND_STATUS_PENDING_REVIEW = 1;
    int SEND_STATUS_SENT = 2;
    int SEND_STATUS_FAILED = 3;
    int SEND_STATUS_REJECTED = 4;

    String DECISION_TYPE_AUTO_SEND = "AUTO_SEND";
    String DECISION_TYPE_MANUAL_CONFIRM = "MANUAL_CONFIRM";
    String DECISION_TYPE_RECORD_ONLY = "RECORD_ONLY";
    String DECISION_TYPE_HUMAN_TAKEOVER = "HUMAN_TAKEOVER";

    String ROUTE_APP_GEWE = "GEWE";

    String REVIEW_STATUS_PENDING = "PENDING";
    String REVIEW_STATUS_APPROVED = "APPROVED";
    String REVIEW_STATUS_EDITED = "EDITED";
    String REVIEW_STATUS_REJECTED = "REJECTED";
    String REVIEW_STATUS_SENT = "SENT";

    int SENSITIVE_MATCH_KEYWORD = 1;
    int SENSITIVE_MATCH_REGEX = 2;
    int SENSITIVE_MATCH_LLM_CLASSIFIER = 3;

    String ESCALATION_TRIGGER_KEYWORD = "KEYWORD";
    String ESCALATION_TRIGGER_REGEX = "REGEX";
    String ESCALATION_TRIGGER_INTENT = "INTENT";
    String ESCALATION_TRIGGER_SENTIMENT = "SENTIMENT";
    String ESCALATION_TRIGGER_CUSTOMER_LEVEL = "CUSTOMER_LEVEL";
    String ESCALATION_TRIGGER_RAG_MISS = "RAG_MISS";
    String ESCALATION_TRIGGER_REQUEST_HUMAN = "REQUEST_HUMAN";

    int SENSITIVE_ACTION_ALLOW = 0;
    int SENSITIVE_ACTION_REVIEW = 1;
    int SENSITIVE_ACTION_BLOCK = 2;
    int SENSITIVE_ACTION_TAKEOVER = 3;

    String EMBEDDING_STATUS_PENDING = "PENDING";
    String EMBEDDING_STATUS_READY = "READY";
    String EMBEDDING_STATUS_FAILED = "FAILED";

    int WEBHOOK_STATUS_NEW = 0;
    int WEBHOOK_STATUS_PROCESSED = 1;
    int WEBHOOK_STATUS_DUPLICATE = 2;
    int WEBHOOK_STATUS_FAILED = 3;

}
